#!/usr/bin/env python3
"""Record every phrase in voice/phrases.txt with a neural Hebrew voice and pack
the clips into voice/voice.js, which the game plays instead of the device's
built-in text-to-speech.

    pip install edge-tts
    python tools/make_voice.py                      # female voice (Hila)
    python tools/make_voice.py --voice he-IL-AvriNeural   # male voice (Avri)

Clips are cached in voice/clips/, so re-running only records phrases that are
new or changed. Uses Microsoft's neural voices through the edge-tts package
(free, no account needed).
"""
import argparse
import asyncio
import base64
import hashlib
import json
import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PHRASES = ROOT / "voice" / "phrases.txt"
CLIPS = ROOT / "voice" / "clips"
OUT = ROOT / "voice" / "voice.js"


def read_phrases():
    """Return (phrase, spoken) pairs. A line 'phrase | spoken' records the
    right-hand spelling under the left-hand key, to fix a pronunciation."""
    pairs = []
    for line in PHRASES.read_text(encoding="utf8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, spoken = line.partition("|")
        pairs.append((key.strip(), (spoken or key).strip()))
    return pairs


async def record(pairs, voice, rate, jobs):
    # Work behind corporate / sandbox proxies that use their own CA bundle.
    ca = os.environ.get("SSL_CERT_FILE") or os.environ.get("REQUESTS_CA_BUNDLE")
    if ca:
        import certifi
        certifi.where = lambda: ca
    import edge_tts

    proxy = os.environ.get("HTTPS_PROXY") or os.environ.get("https_proxy")
    CLIPS.mkdir(parents=True, exist_ok=True)
    sem = asyncio.Semaphore(jobs)
    done = 0

    async def one(key, spoken):
        nonlocal done
        name = hashlib.sha1(f"{voice}|{rate}|{spoken}".encode()).hexdigest()[:16] + ".mp3"
        path = CLIPS / name
        if not path.exists() or path.stat().st_size == 0:
            async with sem:
                for attempt in range(4):
                    try:
                        await edge_tts.Communicate(spoken, voice, rate=rate, proxy=proxy).save(str(path))
                        break
                    except Exception as e:  # network hiccup: retry with backoff
                        if attempt == 3:
                            raise RuntimeError(f"could not record {key!r}: {e}") from e
                        await asyncio.sleep(2 ** attempt)
        done += 1
        print(f"\r{done}/{len(pairs)}", end="", flush=True)
        return key, path

    results = await asyncio.gather(*(one(k, s) for k, s in pairs))
    print()
    return results


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--voice", default="he-IL-HilaNeural", help="he-IL-HilaNeural (female) or he-IL-AvriNeural (male)")
    ap.add_argument("--rate", default="-10%", help="speaking speed, e.g. -10%% is a bit slower than normal")
    ap.add_argument("--jobs", type=int, default=6, help="phrases recorded at the same time")
    args = ap.parse_args()

    pairs = read_phrases()
    results = asyncio.run(record(pairs, args.voice, args.rate, args.jobs))
    clips = {key: base64.b64encode(path.read_bytes()).decode() for key, path in results}
    OUT.write_text(
        f"// Generated by tools/make_voice.py ({args.voice}, rate {args.rate}). Do not edit by hand.\n"
        "window.VOICE_CLIPS = " + json.dumps(clips, ensure_ascii=False, indent=0) + ";\n",
        encoding="utf8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {len(clips)} clips, {OUT.stat().st_size / 1e6:.1f} MB")


if __name__ == "__main__":
    sys.exit(main())
